// Cloudflare bindings augmentations.
//
// `worker-configuration.d.ts` is generated by `wrangler types` from
// wrangler.jsonc (it declares the global `Env` interface with `DB`, the vars,
// and the workerd runtime types). Re-run it whenever bindings change:
//
//   npm run cf-typegen
//
// This file only adds the extras TypeScript needs and is safe to commit.

/// <reference types="@cloudflare/workers-types" />

declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./workers/app");
  }
}
